version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: "mysql"
        hostname: "mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: wordpress_pass
        volumes:
            - ./db_data:/var/lib/mysql
    wordpress:
        image: wordpress:latest
        container_name: "wordpress"
        hostname: "wordpress"
        ports:
            - "8080:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_NAME: wordpress_db
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: wordpress_pass
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - mysql
